//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MentorToken
    {
        public int Id { get; set; }
        public Nullable<int> MentorId { get; set; }
        public string Createdat { get; set; }
        public string Expiredat { get; set; }
        public string Token { get; set; }
    }
}
