//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int Id { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string AnnouncedBy { get; set; }
        public Nullable<int> InstitutionId { get; set; }
        public string Details { get; set; }
        public string Date { get; set; }
        public Nullable<int> MentorId { get; set; }
    
        public virtual Institution Institution { get; set; }
        public virtual Mentor Mentor { get; set; }
    }
}
